# Support Vector Machines Starts From Here

In [1]:
# Importing Libraries

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score, confusion_matrix

import matplotlib.pyplot as plt

import seaborn as sbn

from sklearn import svm


In [2]:
# importing the data file

dfile = pd.read_csv("Diabetes.csv")
dfile.head()

Pragnency  Glucose  Blod Pressure  Skin Thikness  Insulin   BMI    DFP  \
0          1       85             66             29        0  26.6  0.351   
1          8      183             64              0        0  23.3  0.672   
2          1       89             66             23       94  28.1  0.167   
3          0      137             40             35      168  43.1  2.288   
4          5      116             74              0        0  25.6  0.201   

   Age  Diabetes  
0   31         0  
1   32         1  
2   21         0  
3   33         1  
4   30         0

In [3]:
# Separating the features

x = dfile[['Age', 'Glucose']]
y = dfile.Diabetes

In [4]:
# Observing the feature

x.head()


Age  Glucose
0   31       85
1   32      183
2   21       89
3   33      137
4   30      116

In [5]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Diabetes, dtype: int64

In [6]:
# Train test split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state = 5)


In [7]:
# Trained data 

x_train.head()

Age  Glucose
140   38      106
358   29      196
143   23      154
673   68       91
121   23      107

In [8]:
y_train.head()

140    0
358    1
143    0
673    0
121    0
Name: Diabetes, dtype: int64

In [9]:
dfile.describe()

Pragnency     Glucose  Blod Pressure  Skin Thikness     Insulin  \
count  767.000000  767.000000     767.000000     767.000000  767.000000   
mean     3.842243  120.859192      69.101695      20.517601   79.903520   
std      3.370877   31.978468      19.368155      15.954059  115.283105   
min      0.000000    0.000000       0.000000       0.000000    0.000000   
25%      1.000000   99.000000      62.000000       0.000000    0.000000   
50%      3.000000  117.000000      72.000000      23.000000   32.000000   
75%      6.000000  140.000000      80.000000      32.000000  127.500000   
max     17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI         DFP         Age    Diabetes  
count  767.000000  767.000000  767.000000  767.000000  
mean    31.990482    0.471674   33.219035    0.348110  
std      7.889091    0.331497   11.752296    0.476682  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243500   24.000000    0.000000  
50%     32.000000    0.371000   29.000000    0.000000  
75%     36.600000    0.625000   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [10]:
# Scaling up the x trained and y trained value

scaler = StandardScaler()
xtrain_s = scaler.fit_transform(x_train)


In [11]:
# Fitting the model

svmmodel = svm.SVC()
svmmodel.fit(xtrain_s, y_train)

SVC()

In [12]:
# Scaling the value of x 

xtest_s = scaler.transform(x_test)
xtest_s

array([[ 0.32140571,  1.042908  ],
       [-0.86496152, -0.23345579],
       [-0.2717779 , -0.10893249],
       [ 0.99932984,  0.1401141 ],
       [-0.01755635, -0.38910991],
       [-0.69548049,  0.1401141 ],
       [ 1.42303243,  0.82499223],
       [ 0.32140571,  0.29576822],
       [-0.52599945, -0.32684826],
       [-0.94970204,  2.10135602],
       [-0.35651842, -0.88720309],
       [ 0.99932984, -0.48250238],
       [ 2.18569708,  2.13248684],
       [-0.35651842, -0.45137156],
       [ 0.66036778,  1.85230943],
       [ 2.86362121, -1.97678194],
       [ 0.32140571, -3.75123891],
       [ 0.40614623, -0.10893249],
       [ 0.74510829, -0.54476403],
       [-0.94970204, -0.91833392],
       [-0.94970204,  0.63820729],
       [-0.61073997,  0.07785245],
       [-0.18703739,  0.1401141 ],
       [-1.03444255, -0.7626798 ],
       [-0.01755635,  0.04672163],
       [-0.94970204,  0.32689905],
       [ 0.74510829,  0.17124492],
       [ 1.33829191,  1.97683272],
       [-0.86496152,

In [13]:
# Predicting the value using the model

ypredict = svmmodel.predict(xtest_s)
ypredict

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1])

In [14]:
# Calculating the accuracy
acc = accuracy_score(y_test, ypredict)
print(f"Accuracy is= {acc:.2%}")


Accuracy is= 75.97%


In [15]:
# Showing the value in xtend

import numpy as np;

xp = np.array(xtrain_s)
ynp = np.array(y_train)

xp



array([[ 0.40614623, -0.45137156],
       [-0.35651842,  2.35040261],
       [-0.86496152,  1.042908  ],
       ...,
       [-1.03444255, -0.66928733],
       [ 1.59251346,  1.47873954],
       [ 1.59251346,  1.29195459]], shape=(613, 2))

In [16]:
ynp

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,